package xuyuji.leetcode.Q0005_LongestPalindromicSubstring;

import org.junit.Before;
import org.junit.Test;

public class CostTimeTest {

	private static String TEST_STR_1 = "ababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababa";

	private Solution1 solution1;
	private Solution2 solution2;
	private Solution3 solution3;
	private Solution4 solution4;

	@Before
	public void setup() {
		solution1 = new Solution1();
		solution2 = new Solution2();
		solution3 = new Solution3();
		solution4 = new Solution4();
	}

	/**
	 * 暴力破解法耗时测试无法通过，注释掉，避免整体测试用例无法通过。
	 * 
	 * @date 2018年4月25日上午11:38:32
	 * @author xuyuji
	 */
	@Test
	// @Test(timeout = 1000)
	public void costTimeTest1() {
		solution1.longestPalindrome(TEST_STR_1);
	}

	@Test(timeout = 1000)
	public void costTimeTest2() {
		solution2.longestPalindrome(TEST_STR_1);
	}

	@Test(timeout = 1000)
	public void costTimeTest3() {
		solution3.longestPalindrome(TEST_STR_1);
	}

	@Test(timeout = 1000)
	public void costTimeTest4() {
		solution4.longestPalindrome(TEST_STR_1);
	}
}
